alert:
- debug
description: Detects remote printer driver load from Detailed File Share in Security logs that are a sign of successful exploitation attempts against print spooler vulnerability CVE-2021-1675 and CVE-2021-34527
filter:
- query:
    query_string:
      query: (winlog.channel:"Security" AND winlog.event_id:"5145" AND winlog.event_data.ShareName.keyword:\\\*\\IPC$ AND winlog.event_data.RelativeTargetName:"spoolss" AND winlog.event_data.AccessMask:"0x3" AND winlog.event_data.ObjectType:"File")
index: winlogbeat-*
name: 8fe1c584-ee61-444b-be21-e9054b229694-CVE-2021-1675-Print-Spooler-Exploitation-IPC-Access
priority: 1
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
