alert:
- debug
description: Identifies when a Kubernetes account access a sensitive objects such as configmaps or secrets.
filter:
- query:
    query_string:
      query: properties.message:("MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/CONFIGMAPS\/WRITE" OR "MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/CONFIGMAPS\/DELETE" OR "MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/SECRETS\/WRITE" OR "MICROSOFT.KUBERNETES\/CONNECTEDCLUSTERS\/SECRETS\/DELETE")
index: filebeat-*
name: 7ee0b4aa-d8d4-4088-b661-20efdf41a04c-Azure-Kubernetes-Secret-or-Config-Object-Access
priority: 3
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
