alert:
- debug
description: Identifies when a application is deleted in Azure.
filter:
- query:
    query_string:
      query: properties.message:("Delete\ application" OR "Hard\ Delete\ application")
index: filebeat-*
name: 410d2a41-1e6d-452f-85e5-abdd8257a823-Azure-Application-Deleted
priority: 3
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
