alert:
- debug
description: Identifies when a application security group is modified or deleted.
filter:
- query:
    query_string:
      query: properties.message:("MICROSOFT.NETWORK\/APPLICATIONSECURITYGROUPS\/WRITE" OR "MICROSOFT.NETWORK\/APPLICATIONSECURITYGROUPS\/DELETE")
index: winlogbeat-*
name: 835747f1-9329-40b5-9cc3-97d465754ce6-Azure-Application-Security-Group-Modified-or-Deleted
priority: 3
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
