alert:
- debug
description: Initial execution of malicious document calls wmic to execute the file with regsvr32
filter:
- query:
    query_string:
      query: ((Image:"\\wbem\\WMIC.exe" OR CommandLine.keyword:*wmic\ * OR OriginalFileName:"wmic.exe" OR Description:"WMI\ Commandline\ Utility") AND ParentPrcessName.keyword:(*winword.exe OR *excel.exe OR *powerpnt.exe))
index: filebeat-*
name: 518643ba-7d9c-4fa5-9f37-baed36059f6a-Office-Applications-Spawning-Wmi-Cli
priority: 2
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
