alert:
- debug
description: Detects Obfuscated Powershell via use Rundll32 in Scripts
filter:
- query:
    query_string:
      query: (ServiceFileName.keyword:/(?i).*&&.*rundll32.*shell32\.dll.*shellexec_rundll.*(value|invoke|comspec|iex).*"/ AND EventID:"4697")
index: filebeat-*
name: cd0f7229-d16f-42de-8fe3-fba365fbcb3a-Invoke-Obfuscation-Via-Use-Rundll32
priority: 2
realert:
  minutes: 0
type: any

import: BaseHive.config
import: BaseTeams.config
import: BaseRule.config
